# Generated by Django 3.2.16 on 2023-05-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230508_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
    ]
