# Generated by Django 3.2.16 on 2023-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230508_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
