# Generated by Django 3.2.16 on 2023-05-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20230524_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
